### PR TITLE
Update/Remove dependencies and devDependencies

### PR DESCRIPTION
**Pull request by klappy**
Most of the dependencies/dev dependencies were out of date and needed updating, so I did the related Babel/Jest. Babel-runtime is no longer needed and Jest/Babel works without it, it should have been in the devDependencies anyway and not made it into the NPM module.

reported by @mandolyte: 

After adding usfm-js to my package.json, I get this warning when I run yarn:
```
warning usfm-js > babel-runtime > core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

The line below is in the "dependencies" section:
```"usfm-js": "^2.0.0"```

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/usfm-js/97)

### CODE REVIEW

**Comment by klappy** [comment]
CodeCov was run on the first commit, see All Checks have Passed.

**Comment by klappy** [comment]
___
*[src/js/filter.js, line 104 at r1](https://reviewable.io/reviews/unfoldingword/usfm-js/97#-LvUzgQM4Tk_xaNyvcEc:-LvWzgQd2h_uJkF1UPuU:b-xufonf) ([raw file](https://github.com/unfoldingword/usfm-js/blob/336b1c9d1e5adcce54aaa223e20d87409db4d85e/src/js/filter.js#L104)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

I'm trying to get my head around the consequences of replacing a deep copy with a shallow copy.  It looks like my intent was to project the original data structure which could be deeply nested.

It seems we would need some unit tests that ensure the original object is not modified with nested verse objects.

</blockquote></details>

Great question. I was considering the same thing when I made the change. 

Elsewhere, I've been using deepFreeze on all my state objects, and then using the spread operator to copy them without any issues.
I know for sure that it is safe using that combo. To which I have inferred that the spread operator method of copying was safe.

If we add in the deepFreeze only to use the spread operator for copying, we are just trading one dependency for another. That defeats the purpose of the change since the intention is to remove unnecessary dependencies.

I may consider reverting this change and just importing `lodash.cloneDeep` as it is available solo and is the only function we use. Apparently its so common they released it without the bloat.

**Comment by klappy** [comment]
___
*[src/js/filter.js, line 104 at r1](https://reviewable.io/reviews/unfoldingword/usfm-js/97#-LvUzgQM4Tk_xaNyvcEc:-LvfTGNZ5MD95bNRvKb5:b-f96pea) ([raw file](https://github.com/unfoldingword/usfm-js/blob/336b1c9d1e5adcce54aaa223e20d87409db4d85e/src/js/filter.js#L104)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Great question. I was considering the same thing when I made the change. 

Elsewhere, I've been using deepFreeze on all my state objects, and then using the spread operator to copy them without any issues.
I know for sure that it is safe using that combo. To which I have inferred that the spread operator method of copying was safe.

If we add in the deepFreeze only to use the spread operator for copying, we are just trading one dependency for another. That defeats the purpose of the change since the intention is to remove unnecessary dependencies.

I may consider reverting this change and just importing `lodash.cloneDeep` as it is available solo and is the only function we use. Apparently its so common they released it without the bloat.


</blockquote></details>

Okay check this out and see what you think.

**Comment by PhotoNomad0** [comment]
@klappy - changed to merge to develop.  Just bump the version number and we should be good.

**Comment by PhotoNomad0** [comment]
@klappy - you need to bump the version number.

**Comment by klappy** [comment]
Sorry for taking so long on that. Should be good to go.

**Comment by klappy** [comment]
___
*[package.json, line 3 at r2](https://reviewable.io/reviews/unfoldingword/usfm-js/97#-Lvg7Afs590tm1Hv7oVk:-LwEqOO77X0aN6HRcGvW:bb6un1j) ([raw file](https://github.com/unfoldingword/usfm-js/blob/7a51ecc883fe6ec66106b8ec0800f58bae31e302/package.json#L3)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Need to bump the version.
</blockquote></details>

Done

**Pull request merged**
